services:
  - type: web
    name: erp-attendance-app
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
